version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: "crihstianmol/researchlab-backend"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    image: "crihstianmol/researchlab-frontend"
    ports:
      - "80:3000"
    links:
      - "backend"