name: docker-heroku CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
#set environment variables 
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'devflow-researchlab' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          docker_compose_file: './docker-compose.yml' 
          heroku_apps: '[{"imagename":"frontend","appname":"researchlab-front","apptype":"web"},{"imagename":"backend","appname":"researchlab-back","apptype":"web"}]'
