name: docker-heroku CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          app_name: 'researchlab-back' # you aplication name
          dockerfile_path: './backend/Dockerfile' # set the path to the folder where the Dockerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} # your heroku email
          api_key: ${{ secrets.HEROKU_API_KEY }} # your heroku api key
          app_name: 'researchlab-front' # you aplication name
          dockerfile_path: './client/Dockerfile' # set the path to the folder where the Dockerfile is located
          options: '' # Docker Build Options
          formation: '' # Docker Dyno Formation. By default is web
